# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/derailed/k9s.git
%global goipath         github.com/derailed/k9s.git
Version:                0.25.21

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      COPYING LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/k9s.git %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license COPYING LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Jul 11 2022 Odilon Sousa <osousa@redhat.com> - 0.25.21-1
- Initial package
